title:              Robben Island Forum
email:              knowle50@msu.edu
description:        A Blog Theme by Start Bootstrap
author:             Eric, Emma & Katie
baseurl:            "/CHI-rapid-dev-1"
url:                "https://katknow.github.io/CHI-rapid-dev-1/"

# Social Profiles
twitter_username:  
github_username:
facebook_username:
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
